//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFE_OnSite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Client")]
        public string Persist_ClientTextState {
            get {
                return ((string)(this["Persist_ClientTextState"]));
            }
            set {
                this["Persist_ClientTextState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Client Location")]
        public string Persist_LocationTextState {
            get {
                return ((string)(this["Persist_LocationTextState"]));
            }
            set {
                this["Persist_LocationTextState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Floor")]
        public string Persist_FloorTextState {
            get {
                return ((string)(this["Persist_FloorTextState"]));
            }
            set {
                this["Persist_FloorTextState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal Persist_FloorNumberState {
            get {
                return ((decimal)(this["Persist_FloorNumberState"]));
            }
            set {
                this["Persist_FloorNumberState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string Persist_MarkerTextState {
            get {
                return ((string)(this["Persist_MarkerTextState"]));
            }
            set {
                this["Persist_MarkerTextState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal Persist_MarkerNumberState {
            get {
                return ((decimal)(this["Persist_MarkerNumberState"]));
            }
            set {
                this["Persist_MarkerNumberState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Persist_MarkerIncrementState {
            get {
                return ((bool)(this["Persist_MarkerIncrementState"]));
            }
            set {
                this["Persist_MarkerIncrementState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enable")]
        public string Persist_FloorEnableState {
            get {
                return ((string)(this["Persist_FloorEnableState"]));
            }
            set {
                this["Persist_FloorEnableState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Persist_FloorDecrementState {
            get {
                return ((bool)(this["Persist_FloorDecrementState"]));
            }
            set {
                this["Persist_FloorDecrementState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public decimal Persist_SweepsCountState {
            get {
                return ((decimal)(this["Persist_SweepsCountState"]));
            }
            set {
                this["Persist_SweepsCountState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Persist_AutoScaleState {
            get {
                return ((bool)(this["Persist_AutoScaleState"]));
            }
            set {
                this["Persist_AutoScaleState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Persist_SaveCsvCheckedState {
            get {
                return ((bool)(this["Persist_SaveCsvCheckedState"]));
            }
            set {
                this["Persist_SaveCsvCheckedState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Full Downlink")]
        public string Persist_Preset {
            get {
                return ((string)(this["Persist_Preset"]));
            }
            set {
                this["Persist_Preset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Persist_2400State {
            get {
                return ((bool)(this["Persist_2400State"]));
            }
            set {
                this["Persist_2400State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enable")]
        public string Persist_AutoNext {
            get {
                return ((string)(this["Persist_AutoNext"]));
            }
            set {
                this["Persist_AutoNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Persist_CheckBox_Band_600_State {
            get {
                return ((bool)(this["Persist_CheckBox_Band_600_State"]));
            }
            set {
                this["Persist_CheckBox_Band_600_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Persist_CheckBox_Band_700_State {
            get {
                return ((bool)(this["Persist_CheckBox_Band_700_State"]));
            }
            set {
                this["Persist_CheckBox_Band_700_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Persist_CheckBox_Band_CEL_State {
            get {
                return ((bool)(this["Persist_CheckBox_Band_CEL_State"]));
            }
            set {
                this["Persist_CheckBox_Band_CEL_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Persist_CheckBox_Band_PCS_State {
            get {
                return ((bool)(this["Persist_CheckBox_Band_PCS_State"]));
            }
            set {
                this["Persist_CheckBox_Band_PCS_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Persist_CheckBox_Band_AWS_State {
            get {
                return ((bool)(this["Persist_CheckBox_Band_AWS_State"]));
            }
            set {
                this["Persist_CheckBox_Band_AWS_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Persist_CheckBox_Band_WCS_State {
            get {
                return ((bool)(this["Persist_CheckBox_Band_WCS_State"]));
            }
            set {
                this["Persist_CheckBox_Band_WCS_State"] = value;
            }
        }
    }
}
